### PR TITLE
Update branding, URL, and readme

### PR DESCRIPTION
**Pull request by ChristopherJennings**
Hi Milan, 

We're making some changes to the sample gallery and I wanted to get your submission for the Ace Code Editor up-to-date. 

I've updated the URL for the Custom Element API, as well as adjusted the Readme for the rebranding and to add a simple deploy option via Netlify. 

If you approave of the changes, I'd also recommend updating the repo name, description, and topics. You can check out my for my suggestions on that, and they're copied below:

Name: kontent-custom-element-ace-code-editor
Desc: Ace Code Editor custom element for Kentico Kontent
Topics: kentico-kontent kontent custom-element ace-editor

Let me know if you have any questions or comments.

### CODE REVIEW

**Comment by ChristopherJennings** [comment]
Hi @MilanLund, 

Do you have any questions on this PR?

**Comment by ChristopherJennings** [comment]
Hi @MilanLund, is there a chance you'll be able to review this and pull it in soon?

**Comment by MilanLund** [comment]
Hey @ChristopherJennings , sorry for the delay. All should be done now. Please, let me know if any more updates are needed.

**Comment by ChristopherJennings** [comment]
Thanks!

**Pull request merged**
